version: '3'

# 声明一个名为forum_net的networks，subnet为forum_net的子网地址，默认网关是172.7.0.1
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  server:
    image: ccr.ccs.tencentyun.com/cherry_forum/forum:1.13
    container_name: forum_server
    hostname: forum_server
    environment:
      # 时区上海 - Timezone Shanghai
      TZ: Asia/Shanghai
    privileged: true
    restart: always
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    command: ["./wait-for.sh","mysql:3306","redis:6379","./forum","./config.docker.yaml"]
    networks:
      network:
        ipv4_address: 172.20.0.12

  mysql:
    image: mysql:8.0.28
    container_name: forum_mysql
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
      MYSQL_DATABASE: 'forum_server'
      # root 密码 - root password
      MYSQL_ROOT_PASSWORD: 'forum123'
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","124.221.205.130"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "13306:3306"
    volumes:
      # 数据挂载 - Data mounting
      - /home/project_forum/mysql/data:/var/lib/mysql
      - /home/project_forum/mysql/conf/conf.d:/etc/mysql/conf.d
     # 日志
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      # Modify the Mysql 8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      network:
         ipv4_address: 172.20.0.13

  redis:
    image: redis:6.2.5
    container_name: forum_redis
    ports:
      - "16379:6379"
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      - /home/project_forum/redis/data:/data
      - /home/project_forum/redis/redis.conf:/etc/redis/redis.conf
    command: "redis-server --requirepass forum123 --appendonly yes"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    privileged: true
    restart: always
    networks:
      network:
        ipv4_address: 172.20.0.14

  nginx-gateway:
    image: nginx:1.21.5
    container_name: forum_nginx_gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9000:8081"
    volumes:
      - /home/project_forum/nginx/conf.d:/etc/nginx/conf.d
      - /home/project_forum/nginx/log:/var/log/nginx
    networks:
      network:
        ipv4_address: 172.20.0.15
    links:
      - server
    depends_on:
      - server
